name: 06-aws-bd

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: itc-org/infra-templates/.github/workflows/aws-deploy-template.yml@main
    with:
      workspace: bd
      role_arn: arn:aws:iam::743737183475:role/github-actions-terraform
      aws_region: eu-west-2
