name: Deploy AWS
run-name: Deploying to ${{ inputs.workspace }}

on:
  workflow_dispatch:
    inputs:
      ec2:
        description: "Deploy EC2"
        type: boolean
        default: false
      ec2_count:
        description: "Number of EC2 instances (1-3)"
        type: choice
        default: "1"
        options:
          - "1"
          - "2"
          - "3"
      eks:
        description: "Deploy eks"
        type: boolean
        default: false
      s3:
        description: "Deploy S3"
        type: boolean
        default: false
      rds:
        description: "Deploy RDS"
        type: boolean
        default: false
      ecr:
        description: "Deploy ECR"
        type: boolean
        default: false
      ecs:
        description: "Deploy ECS"
        type: boolean
        default: false
      lambda:
        description: "Deploy Lambda"
        type: boolean
        default: false
      sns:
        description: "Deploy SNS"
        type: boolean
        default: false
      codecommit:
        description: "Deploy CodeCommit"
        type: boolean
        default: false
      codebuild:
        description: "Deploy CodeBuild"
        type: boolean
        default: false
      codepipeline:
        description: "Deploy CodePipeline"
        type: boolean
        default: false
      glue:
        description: "Deploy Glue"
        type: boolean
        default: false
      opensearch:
        description: "Deploy OpenSearch"
        type: boolean
        default: false
      sagemaker:
        description: "Deploy SageMaker"
        type: boolean
        default: false
      quicksight:
        description: "Deploy QuickSight"
        type: boolean
        default: false
      redshift:
        description: "Deploy redshift"
        type: boolean
        default: false
      sqs:
        description: "Deploy SQS"
        type: boolean
        default: false
      apigw:
        description: "Deploy API Gateway"
        type: boolean
        default: false
      bedrock_agent:
        description: "Deploy Bedrock Agent"
        type: boolean
        default: false
      bedrock_kb:
        description: "Deploy Bedrock Knowledge Base"
        type: boolean
        default: false


      workspace:
        description: "Workspace"
        required: true
        default: "aws1"
        type: choice
        options:
          - java
          - ds
          - do
          - bd
          - pmo


permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws   

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ########################################
      # AWS LOGIN (OIDC)
      ########################################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::666127452756:role/terraform-deployer-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      #########################################
      # Workspace Select / Create
      ########################################
      - name: Select or Create Workspace
        run: |
          terraform workspace select ${{ inputs.workspace }} || \
          terraform workspace new ${{ inputs.workspace }}

      ########################################
      # Build services list
      ########################################
      - name: Build services list
        id: build
        run: |
          SERVICES="["
          [ "${{ inputs.ec2 }}" == "true" ] && SERVICES="$SERVICES\"ec2\","
          [ "${{ inputs.eks }}" == "true" ] && SERVICES="$SERVICES\"eks\","
          [ "${{ inputs.s3 }}" == "true" ] && SERVICES="$SERVICES\"s3\","
          [ "${{ inputs.rds }}" == "true" ] && SERVICES="$SERVICES\"rds\","
          [ "${{ inputs.ecr }}" == "true" ] && SERVICES="$SERVICES\"ecr\","
          [ "${{ inputs.lambda }}" == "true" ] && SERVICES="$SERVICES\"lambda\","
          [ "${{ inputs.sns }}" == "true" ] && SERVICES="$SERVICES\"sns\","
          [ "${{ inputs.codecommit }}" == "true" ] && SERVICES="$SERVICES\"codecommit\","
          [ "${{ inputs.codebuild }}" == "true" ] && SERVICES="$SERVICES\"codebuild\","
          [ "${{ inputs.codepipeline }}" == "true" ] && SERVICES="$SERVICES\"codepipeline\","
          [ "${{ inputs.glue }}" == "true" ] && SERVICES="$SERVICES\"glue\","
          [ "${{ inputs.opensearch }}" == "true" ] && SERVICES="$SERVICES\"opensearch\","
          [ "${{ inputs.sagemaker }}" == "true" ] && SERVICES="$SERVICES\"sagemaker\","
          [ "${{ inputs.quicksight }}" == "true" ] && SERVICES="$SERVICES\"quicksight\","
          [ "${{ inputs.redshift }}" == "true" ] && SERVICES="$SERVICES\"redshift\","
          [ "${{ inputs.ecs }}" == "true" ] && SERVICES="$SERVICES\"ecs\","
          [ "${{ inputs.sqs }}" == "true" ] && SERVICES="$SERVICES\"sqs\","
          [ "${{ inputs.apigw }}" == "true" ] && SERVICES="$SERVICES\"apigw\","
          [ "${{ inputs.bedrock_agent }}" == "true" ] && SERVICES="$SERVICES\"bedrock-agent\","
          [ "${{ inputs.bedrock_kb }}" == "true" ] && SERVICES="$SERVICES\"bedrock-kb\","

          
          SERVICES="${SERVICES%,}]"
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

      - name: Debug services list
        run: echo "Services = ${{ steps.build.outputs.services }}"

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var='services_to_deploy=${{ steps.build.outputs.services }}' -out=tfplan
        env:
          TF_VAR_ec2_instance_count: ${{ inputs.ec2_count }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan